### ISSUE TITLE
Menu bug in main spectrum

### ISSUE THREAD

**Issue by asodini** [DAS-OATs/astrocook#259]
When you right-click on the main spectrum (for example to remove or add a node to the continuum, or to fit a new system) the drop-down menu does not appear and the following error code appears.
![Immagine 2022-11-29 110913](https://user-images.githubusercontent.com/119429586/204563562-65c35985-b9ef-4d08-8788-59baea7d270c.jpg)

**Comment by asodini** [comment]
I use Ubuntu 16.04.7 OS.
I don't know if it happens with every session, I updated the develop branch and in the first session I opened I encountered this problem. Then, I immediately went back to the previous version.

**Comment by gcupani** [comment]
I think I fixed it. Could you please checkout branch [fix/issue_259](https://github.com/DAS-OATs/astrocook/tree/fix/issue_259) and confirm that it works?

**Comment by asodini** [comment]
Now when I right-click on the spectrum the drop-down menu comes out correctly. However, if in an .acs session in which no lines have been fitted I click on the 'Redshift cursor' in the 'View' menu, the 'System controls' window exits correctly but in the main spectrum there is no cursor and consequently in the drop-down menu obtained by right-clicking, there is no 'New system' item.

**Comment by gcupani** [comment]
I should have fixed also the disappearance of the cursor. Please try again.

**Comment by asodini** [comment]
The cursor now appears, but the 'New system' item is not yet in the drop-down menu that appears after right-clicking.

**Comment by gcupani** [comment]
Is the continuum present in the spectrum you are using (`cont` column)? If not, the “New system” item is expected not to appear.

**Comment by asodini** [comment]
Ok, I was trying in a spectrum without the continuum. I also added a continuum fit and now the 'New system' item appears correctly, thank you.

**Comment by gcupani** [comment]
Thank you for the feedback! I am closing the issue (it can be re-opened if needed) and merging the changes into develop.
