### ISSUE TITLE
lines_voigt generates incorrect optical depth profile at very high column densities

### ISSUE THREAD

**Issue by rdavies193** [DAS-OATs/astrocook#285]
It seems that lines_voigt does not return the correct optical depth profile in the collisional-broadening-dominated regime. 
In particular, no matter the b parameter or column density, I could not get the code to generate profiles with collisional broadening wings.
The attached plot shows the expected absorption profile vs. the one returned by lines_voigt for series = 'NaI_5891,NaI_5897', b = 10 km/s, logN = 17.
After much digging, I think the issue arises from the 'a' parameter passed to _fadd, and specifically, it seems to be 12 orders of magnitude too small. If i comment out line 68, a = a * 1e-12, then the generated profile matches the expected one perfectly (see second attached plot).
![absorption_profile](https://user-images.githubusercontent.com/59436029/224232787-ebbc0cb3-c80f-4b8f-86a6-8da0a19feb71.png)
![absorption_profile_adjusted](https://user-images.githubusercontent.com/59436029/224233251-64c18772-c729-4bca-a6f6-84f01eae9ec0.png)

**Comment by gcupani** [comment]
Hi,
this is very strange. Thanks for pointing it out.
Just a check, are you sure you are not unknowingly putting an upper limit on logN (logN_max in vars.py)? When you try to fit a line with logN above the limit, the actual value of logN is logN_max, even though it doesn't appear from the system table.
Which version are you using? I assume 1.5.1 (master branch). Could you please switch to the develop branch and tell me if the problem arises anyway?
Could you please send me the script you are using to produce the plot?
Guido

**Comment by rdavies193** [comment]
Hi Guido,
I'm very sorry for the false alarm, it seems that this was a bug in my fork of astrocook. I thought my functions file was the same as yours but next time I will check!! I never noticed this problem before because it only impacts the output for strongly saturated line profiles which I did not encounter when constructing the metal line catalogue.

**Comment by gcupani** [comment]
Don't worry, and thank you for reporting the issue anyway. I am glad it didn't affect the metal line catalogue. 
For me, it is also a good reminder to merge the changes into the master more often… will do it soon! ;-)
