### ISSUE TITLE
Import a normalized spectrum with generic format does not load y and dy

### ISSUE THREAD

**Issue by G-Francio** [DAS-OATs/astrocook#310]
Basically title: if one imports a spectrum in the generic format where 0.7 < `np.median(y)*np.max(y)` < 1.3, the imported spectrum will have `y` and `dy` filled with `nan`s.
I believe the cause of the issue is at line 539/540 of format.py; commenting those out loads the spectrum correctly.

I'll try to provide a fix for this

**Comment by gcupani** [comment]
Possibly solved by @G-Francio (PR: https://github.com/DAS-OATs/astrocook/pull/311). 
Waiting for testing before merging it into `develop`.

**Comment by gcupani** [comment]
Merged into `develop`.
